# _config.yml
title: ""
email: "leonrob34@ya.ru"
description: "Геймдизайнер, сценарист, программист — портфолио и кейсы"
baseurl: "/TerunPfolio"       # путь к сайту от корня домена
url: "https://brotherterun.github.io" # основной домен сайта, нужен для OpenGraph, RSS, sitemap и абсолютных ссылок (можно оставить для SEO, но для внутренних ссылок можно ориентироваться на relative_url)
theme: minima     # можно использовать собственную верстку; minima — лёгкий старт
plugins: []
collections:
  projects:
    output: true
    permalink: /projects/:name/
paginate: 6
